import Container from "@mui/material/Container";

export default function EventList() {

    return (<div>
                <Container style={{maxHeight: 500, overflow: 'auto', border: "groove"}}>
                    Events
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.

                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.

                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.

                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.

                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim maxime obcaecati rem tempore voluptatibus. Doloremque ea excepturi illo magnam quisquam similique. Aliquid consequatur expedita laboriosam magni nemo, nostrum quis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquam debitis error non ratione! Consequatur debitis enim ex harum neque quasi quia sunt, totam voluptates! Asperiores facere ipsum sin
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A architecto blanditiis cumque dolor dolore doloribus earum eius expedita iure labore magnam nam nesciunt quis sed similique ut vero, voluptatem voluptates!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae cumque doloribus eum exercitationem in labore molestias nemo, nesciunt nihil omnis optio porro quae quas recusandae totam, veritatis. Maxime, omnis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum explicabo natus obcaecati quibusdam, quis ullam vel. Corporis delectus distinctio dolorem eaque iure, iusto soluta! Aspernatur culpa nisi odit quia.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti dignissimos dolorem dolores et id incidunt nam, odio omnis quas quibusdam quis recusandae rem voluptates voluptatibus! Ab accusamus itaque sit.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto beatae earum, eos facilis minus modi quos repellendus sapiente totam vitae? Harum impedit in labore minima quod recusandae repudiandae totam, voluptatum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aperiam aut commodi corporis distinctio doloribus, dolorum ea enim exercitationem, inventore maxime minus nulla perferendis quas ratione recusandae reprehenderit repudiandae sunt?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque autem dolore ducimus est eum explicabo harum, ipsam maxime molestias non nostrum odio omnis pariatur quia reiciendis tempore veniam voluptate voluptatem.

                </Container>
        </div>
    );
}
