# Define the pipeline stages
stages:
  - build
  - deploy

# Define the build job
build:
  image: node:latest
  stage: build
  script:
    # Install dependencies
    - yarn install
    # Build the Next.js app
    - yarn build

# Define the deploy job
deploy:
  image: node:latest
  stage: deploy
  dependencies:
    - build
  script:
    # Install Firebase CLI
    - yarn global add firebase-tools
    # Authenticate with Firebase
    - echo $FIREBASE_TOKEN | firebase login:ci
    # Deploy to Firebase Hosting
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  environment:
    name: production
  only:
    - master
